'use strict';
// ============================================================
//  MAPS: tile layouts, warps, signs, connections
//  Legend (outdoor):  . grass  : path  ^ gravel  " tall grass  T tree  W water  f flowers  # fence
//                     L ledge  S sign  k bush  x rock  R/B/C/O/G/M roofs  H wall  w window  D door
//  Legend (indoor):   | wall  _ wood  q tile  g gym floor  ~ mat  > stairs  n shelf  t table  y plant
//                     c counter  P pc  V tv  h healer  o lab table  K machine  E bed  X boulder  Z statue
// ============================================================
// warp types: door (walk into), mat (press dir while standing on), step (step onto)
const HOUSE_ROWS = [
  '||||||||||||',
  '|nn______nn|',
  '|__________|',
  '|____tt____|',
  '|____tt____|',
  '|__________|',
  '|y________y|',
  '|||||~~|||||',
];
const CENTER_ROWS = [
  '||||||||||||||',
  '|qqqhqqqqqyqq|',
  '|cccccccccqPq|',
  '|qqqqqqqqqqqq|',
  '|qqqqqqqqqqqq|',
  '|yqqqqqqqqqqy|',
  '|qqqqqqqqqqqq|',
  '|qqqqqqqqqqqq|',
  '||||||~~||||||',
];
const MART_ROWS = [
  '||||||||||||',
  '|qqqqqnnnnq|',
  '|qqqqqqqqqq|',
  '|qcqqqnnnnq|',
  '|qcqqqqqqqq|',
  '|qcqqqnnnnq|',
  '|qqqqqqqqqq|',
  '|||||~~|||||',
];
const GATE_ROWS = [
  '||||__||||',
  '|________|',
  '|y______y|',
  '|________|',
  '|________|',
  '|________|',
  '|________|',
  '||||~~||||',
];
const matWarps = (xs, y, to, tx, ty) => xs.map(x => ({ x, y, to, tx, ty, dir: 0, type: 'mat', face: 0 }));

const MAPS = {
  pallet: {
    name: 'PALLET TOWN', outdoor: true, ground: '.',
    rows: [
      'TTTTTTTTT..TTTTTTTTT',
      'T........::........T',
      'T..RRRR..::..RRRR..T',
      'T..RRRR..::..RRRR..T',
      'T..HwDH..::..HwDH..T',
      'T..S.....::...S....T',
      'T........::........T',
      'T.......:::........T',
      'T..fff..:...OOOOO..T',
      'T..fff..:...OOOOO..T',
      'T.......:...HwDwH..T',
      'T.......:::::::....T',
      'T...S...:......S...T',
      'T.####..:..........T',
      'T.......:....ffff..T',
      'T..WWWW.:..........T',
      'T..WWWW.:..........T',
      'TTWWWWWTTTTTTTTTTTTT',
    ],
    conn: { north: { map: 'route1', off: 0 } },
    warps: [
      { x: 5, y: 4, to: 'house1f', tx: 5, ty: 7, dir: 1, type: 'door' },
      { x: 15, y: 4, to: 'rivalHouse', tx: 5, ty: 7, dir: 1, type: 'door' },
      { x: 14, y: 10, to: 'lab', tx: 5, ty: 11, dir: 1, type: 'door' },
    ],
    signs: [
      { x: 3, y: 5, text: "{PLAYER}'s house" },
      { x: 14, y: 5, text: "{RIVAL}'s house" },
      { x: 4, y: 12, text: 'PALLET TOWN\nShades of your journey await!' },
      { x: 15, y: 12, text: 'OAK POKéMON RESEARCH LAB' },
    ],
  },
  route1: {
    name: 'ROUTE 1', outdoor: true, ground: '.', enc: 'route1',
    rows: [
      'TTTTTTTTT..TTTTTTTTT',
      'T........::........T',
      'T.""""...::..."""".T',
      'T.""""...::..."""".T',
      'T.""""...::..."""".T',
      'T........::........T',
      'TLLLLLLL.::.LLLLLLLT',
      'T........::........T',
      'T..TT....::....""""T',
      'T..TT..S.::....""""T',
      'T........::....""""T',
      'T""""....::........T',
      'T""""....::...TTT..T',
      'T""""....::........T',
      'T........::........T',
      'TLLLL.LLLLLLLLLLLLLT',
      'T........::........T',
      'T..""""..::..""""..T',
      'T..""""..::..""""..T',
      'T........::........T',
      'T...TT...::........T',
      'T...TT...::..TT....T',
      'T........::........T',
      'TLLLLLLLLLL..LLLLLLT',
      'T........::........T',
      'T.""""...::..."""".T',
      'T.""""...::........T',
      'T........::........T',
      'T........::........T',
      'TTTTTTTTT..TTTTTTTTT',
    ],
    conn: { north: { map: 'viridian', off: 6 }, south: { map: 'pallet', off: 0 } },
    warps: [],
    signs: [{ x: 7, y: 9, text: 'ROUTE 1\nPALLET TOWN - VIRIDIAN CITY' }],
  },
  viridian: {
    name: 'VIRIDIAN CITY', outdoor: true, ground: '.',
    rows: [
      'TTTTTTTTTTTTTTT..TTTTTTTTTTTTTTT',
      'T..............::..............T',
      'T..............::....GGGGGG....T',
      'T..WWWW........::....GGGGGG....T',
      'T..WWWW........::....HHwDHH....T',
      'T..WWWW...S....::.......:......T',
      'T..............:::::::::::.....T',
      'T......RRRR....::..............T',
      '.......RRRR....::.......BBBB...T',
      '.......HwDH....::.......BBBB...T',
      '.......:.......::.......HwDH...T',
      '::::::::::::::::::::::::::::...T',
      'T..............::..............T',
      'T...CCCC.......::....RRRR......T',
      'T...CCCC.......::....RRRR......T',
      'T...HwDH.......::....HwDH......T',
      'T.....:........::.....:........T',
      'T...S....ffff..::..ffff...S....T',
      'T..............::..............T',
      'TTTTTTTTTTTTTTT..TTTTTTTTTTTTTTT',
    ],
    conn: { south: { map: 'route1', off: -6 }, north: { map: 'route2', off: -6 }, west: { map: 'route22', off: -5 } },
    warps: [
      { x: 6, y: 15, to: 'viridianCenter', tx: 6, ty: 8, dir: 1, type: 'door' },
      { x: 26, y: 10, to: 'viridianMart', tx: 5, ty: 7, dir: 1, type: 'door' },
      { x: 9, y: 9, to: 'viridianSchool', tx: 5, ty: 7, dir: 1, type: 'door' },
      { x: 23, y: 15, to: 'viridianHouse', tx: 5, ty: 7, dir: 1, type: 'door' },
      { x: 24, y: 4, locked: 'viridianGym', type: 'door' },
    ],
    signs: [
      { x: 10, y: 5, text: 'VIRIDIAN CITY\nThe Eternally Green Paradise' },
      { x: 4, y: 17, text: 'TRAINER TIPS\fCatch POKéMON and expand your collection.\fThe more you have, the easier it is to battle.' },
      { x: 26, y: 17, text: 'TRAINER TIPS\fThe battle moves of POKéMON are limited by their POWER POINTS, PP.\fTo replenish PP, rest your tired POKéMON at a POKéMON CENTER.' },
    ],
  },
  route22: {
    name: 'ROUTE 22', outdoor: true, ground: '.', enc: 'route22',
    rows: [
      'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
      'T.......""""""""..........TTTT',
      'T.......""""""""...........TTT',
      'T........""""""...............',
      'T..............LLLLLLL........',
      'T...""""......................',
      'T...""""..........""""""......',
      'T...""""..........""""""....TT',
      'T.................""""""...TTT',
      'T..S.......................TTT',
      'T..........................TTT',
      'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
    ],
    conn: { east: { map: 'viridian', off: 5 } },
    warps: [],
    signs: [{ x: 3, y: 9, text: 'ROUTE 22\nPOKéMON LEAGUE FRONT GATE\fThe road ahead is closed to TRAINERS without BADGES.' }],
  },
  route2: {
    name: 'ROUTE 2', outdoor: true, ground: '.', enc: 'route2',
    rows: [
      'TTTTTTTTTTTTTTTTTTTT',
      'TTTTTTTTTTTTTTTTTTTT',
      'TT...RRRRRR........T',
      'TT...RRRRRR........T',
      'TT...HHwDwH........T',
      'TT......:..........T',
      'TT......:...""""...T',
      'T.......:...""""...T',
      'T.""""..:...""""...T',
      'T.""""..:..........T',
      'T.""""..::::.......T',
      'T..........:.......T',
      'T.LLLLLLLL.:LLLLLL.T',
      'T..........:.......T',
      'T..""""""..:.......T',
      'T..""""""..:...S...T',
      'T..""""""..:.......T',
      'T..........:.......T',
      'T.........::.......T',
      'T.........:........T',
      'T.......""""""""...T',
      'T.......""""""""...T',
      'T.......""""""""...T',
      'T.........::.......T',
      'T.........::.......T',
      'T.LLLLLLL.::.LLLLL.T',
      'T........::........T',
      'T........::........T',
      'T........::........T',
      'TTTTTTTTT..TTTTTTTTT',
    ],
    conn: { south: { map: 'viridian', off: 6 } },
    warps: [{ x: 8, y: 4, to: 'gateS', tx: 4, ty: 7, dir: 1, type: 'door' }],
    signs: [{ x: 15, y: 15, text: 'ROUTE 2\nVIRIDIAN CITY - PEWTER CITY' }],
  },
  gateS: {
    name: 'VIRIDIAN FOREST', floor: '_',
    rows: GATE_ROWS,
    warps: [
      ...matWarps([4, 5], 7, 'route2', 8, 5),
      { x: 4, y: 0, to: 'forest', tx: 26, ty: 32, dir: 1, type: 'step' },
      { x: 5, y: 0, to: 'forest', tx: 27, ty: 32, dir: 1, type: 'step' },
    ],
    signs: [],
  },
  forest: {
    name: 'VIRIDIAN FOREST', outdoor: true, ground: '.', enc: 'forest', dungeon: true, border: 'T',
    rows: [
      'TT::TTTTTTTTTTTTTTTTTTTTTTTTTT',
      'T....""""""""TTT......"""".TTT',
      'T....""""""""TTT......"""".TTT',
      'T..TTTTTTTT..TTT..TT..TTTT.TTT',
      'T..TTTTTTTT.......TT..TTTT.TTT',
      'T""TT....TT.......TT.......TTT',
      'T""TT."".TTTTTTT..TT.......TTT',
      'T""TT.""..........TTTTTTTT.TTT',
      'T..TT....TTTTTTT..TTTTTTTT.TTT',
      'T..TTTTTTTT.......""""......TT',
      'T.........."""""..""""......TT',
      'T.........."""""..TTTTTTTT..TT',
      'TTTTTTT..TTTTTTT..TTTTTTTT..TT',
      'T"""".......TTTT..TT........TT',
      'T"""".......TTTT..TT........TT',
      'T""""..TTT..TTTT..TT..TTTTTTTT',
      'T..TT..TTT........""..TTTTTTTT',
      'T..TT..TTT........"".......TTT',
      'T..TT..TTTTTTTTTTTTTTTTTT..TTT',
      'T..TT..........""""""....T..TT',
      'T..TTTTTTTTTT..""""""....T..TT',
      'T..TTTTTTTTTT..TTTTTTTT..T..TT',
      'T.............TTTTTTTT.......T',
      'T""""""""""...TTTTTTTT.......T',
      'T""""""""""...TT...""""""""..T',
      'TTTTTTTTTT....TT...""""""""..T',
      'TTTTTTTTTT....TT...TTTTTTTT..T',
      'T..........""".....TTTTTTTT..T',
      'T..........""".......""""....T',
      'T..TTTTTTTTTTTTTTTTTT""""....T',
      'T.......................TT...T',
      'T.......................TT...T',
      'TTTTTTTTTTTTTTTTTTTTTTTTT...TT',
      'TTTTTTTTTTTTTTTTTTTTTTTTTT::TT',
    ],
    warps: [
      { x: 2, y: 0, to: 'gateN', tx: 4, ty: 7, dir: 1, type: 'step' },
      { x: 3, y: 0, to: 'gateN', tx: 5, ty: 7, dir: 1, type: 'step' },
      { x: 26, y: 33, to: 'gateS', tx: 4, ty: 1, dir: 0, type: 'step' },
      { x: 27, y: 33, to: 'gateS', tx: 5, ty: 1, dir: 0, type: 'step' },
    ],
    signs: [],
  },
  gateN: {
    name: 'VIRIDIAN FOREST', floor: '_',
    rows: GATE_ROWS,
    warps: [
      ...matWarps([4, 5], 7, 'forest', 2, 1),
      { x: 4, y: 0, to: 'route2n', tx: 7, ty: 10, dir: 0, type: 'step' },
      { x: 5, y: 0, to: 'route2n', tx: 7, ty: 10, dir: 0, type: 'step' },
    ],
    signs: [],
  },
  route2n: {
    name: 'ROUTE 2', outdoor: true, ground: '.', enc: 'route2',
    rows: [
      'TTTTTTTTT..TTTTTTTTT',
      'T........::........T',
      'T..""""..::........T',
      'T..""""..::..""""..T',
      'T........::..""""..T',
      'T........::........T',
      'T..S.....::........T',
      'T...RRRRRR.........T',
      'T...RRRRRR.........T',
      'T...HHwDwH.........T',
      'T......:...........T',
      'TTTTTTTTTTTTTTTTTTTT',
    ],
    conn: { north: { map: 'pewter', off: 6 } },
    warps: [{ x: 7, y: 9, to: 'gateN', tx: 4, ty: 1, dir: 0, type: 'door' }],
    signs: [{ x: 3, y: 6, text: 'ROUTE 2\nVIRIDIAN CITY - PEWTER CITY' }],
  },
  pewter: {
    name: 'PEWTER CITY', outdoor: true, ground: '^',
    rows: [
      'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
      'T^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^T',
      'T^^^MMMMMMMM^^^^^^^^^^^^^^^^^^^T',
      'T^^^MMMMMMMM^^^^^^^^^^^^^^^^^^^T',
      'T^^^HHHwDwHH^^^^^^^^^^^^^^^^^^^T',
      'T^^^^^^^:^^^^^^^S^^^^^^^^^^^^^^T',
      'T^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^T',
      'T^^^^^^GGGGGG^^^^^^^^^^RRRR^^^^T',
      'T^^^^^^GGGGGG^^^^^^^^^^RRRR^^^^T',
      'T^^^^^^GGGGGG^^^^^^^^^^HwDH^^^^T',
      'T^^^^^^HHwDwH^^^^^^^^^^^^^^^^^^^',
      'T^^^^^^^^^^^^^^S^^^^^^^^^^^^^^^^',
      'T^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^',
      'T^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^',
      'T^^^^^^^^^^^^^^^^^^^BBBB^^^^^^^T',
      'T^^^CCCC^^^^^^^^^^^^BBBB^^^^^^^T',
      'T^^^CCCC^^^^^^^^^^^^HwDH^^^^^^^T',
      'T^^^HwDH^^^^^^^^^^^^^^^^^^^^^^^T',
      'T^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^T',
      'T^^xx^^^^^^^^^^^^^^^^^^^^^^xx^^T',
      'T^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^T',
      'T^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^T',
      'TTTTTTTTTTTTTTT^^TTTTTTTTTTTTTTT',
    ],
    conn: { south: { map: 'route2n', off: -6 } },
    warps: [
      { x: 6, y: 17, to: 'pewterCenter', tx: 6, ty: 8, dir: 1, type: 'door' },
      { x: 22, y: 16, to: 'pewterMart', tx: 5, ty: 7, dir: 1, type: 'door' },
      { x: 10, y: 10, to: 'pewterGym', tx: 4, ty: 13, dir: 1, type: 'door' },
      { x: 25, y: 9, to: 'pewterHouse', tx: 5, ty: 7, dir: 1, type: 'door' },
      { x: 8, y: 4, locked: 'museum', type: 'door' },
    ],
    signs: [
      { x: 16, y: 5, text: 'PEWTER MUSEUM OF SCIENCE' },
      { x: 15, y: 11, text: 'PEWTER CITY\nA Stone Gray City' },
    ],
  },
  // ---------- interiors ----------
  house1f: {
    name: 'PALLET TOWN', floor: '_',
    rows: [
      '||||||||||||',
      '|nn__V____>|',
      '|__________|',
      '|____tt____|',
      '|____tt____|',
      '|__________|',
      '|y________y|',
      '|||||~~|||||',
    ],
    warps: [...matWarps([5, 6], 7, 'pallet', 5, 5), { x: 10, y: 1, to: 'house2f', tx: 9, ty: 1, dir: 2, type: 'step' }],
    signs: [],
  },
  house2f: {
    name: 'PALLET TOWN', floor: '_',
    rows: [
      '||||||||||||',
      '|P__V_____>|',
      '|__________|',
      '|__________|',
      '|__________|',
      '|E_________|',
      '|E____y____|',
      '||||||||||||',
    ],
    warps: [{ x: 10, y: 1, to: 'house1f', tx: 9, ty: 1, dir: 2, type: 'step' }],
    signs: [],
  },
  rivalHouse: { name: 'PALLET TOWN', floor: '_', rows: HOUSE_ROWS, warps: matWarps([5, 6], 7, 'pallet', 15, 5), signs: [] },
  lab: {
    name: 'PALLET TOWN', floor: '_',
    rows: [
      '||||||||||||',
      '|KKKK__nnnn|',
      '|__________|',
      '|______ooo_|',
      '|__________|',
      '|__________|',
      '|nnnn__nnnn|',
      '|__________|',
      '|__________|',
      '|KK______KK|',
      '|__________|',
      '|||||~~|||||',
    ],
    warps: matWarps([5, 6], 11, 'pallet', 14, 11),
    signs: [],
  },
  viridianCenter: { name: 'VIRIDIAN CITY', floor: 'q', center: true, rows: CENTER_ROWS, warps: matWarps([6, 7], 8, 'viridian', 6, 16), signs: [] },
  viridianMart: { name: 'VIRIDIAN CITY', floor: 'q', rows: MART_ROWS, warps: matWarps([5, 6], 7, 'viridian', 26, 11), signs: [] },
  viridianSchool: { name: 'VIRIDIAN CITY', floor: '_', rows: HOUSE_ROWS, warps: matWarps([5, 6], 7, 'viridian', 9, 10), signs: [] },
  viridianHouse: { name: 'VIRIDIAN CITY', floor: '_', rows: HOUSE_ROWS, warps: matWarps([5, 6], 7, 'viridian', 23, 16), signs: [] },
  pewterCenter: { name: 'PEWTER CITY', floor: 'q', center: true, rows: CENTER_ROWS, warps: matWarps([6, 7], 8, 'pewter', 6, 18), signs: [] },
  pewterMart: { name: 'PEWTER CITY', floor: 'q', rows: MART_ROWS, warps: matWarps([5, 6], 7, 'pewter', 22, 17), signs: [] },
  pewterHouse: { name: 'PEWTER CITY', floor: '_', rows: HOUSE_ROWS, warps: matWarps([5, 6], 7, 'pewter', 25, 10), signs: [] },
  pewterGym: {
    name: 'PEWTER CITY', floor: 'g', battleBg: 'indoor',
    rows: [
      '||||||||||',
      '|gggggggg|',
      '|gggggggg|',
      '|gXXggXXg|',
      '|gggggggg|',
      '|gggggggg|',
      '|XXXggXXX|',
      '|gggggggg|',
      '|gggggggg|',
      '|gXXggXXg|',
      '|gggggggg|',
      '|ZggggggZ|',
      '|gggggggg|',
      '||||~~||||',
    ],
    warps: matWarps([4, 5], 13, 'pewter', 10, 11),
    signs: [],
  },
};
for (const id in MAPS) { MAPS[id].id = id; MAPS[id].npcs = MAPS[id].npcs || []; MAPS[id].triggers = MAPS[id].triggers || []; }
