#!/usr/bin/env python3
"""Extract FRLG latin fonts (glyph masks, widths) + charmap. usage: build_font.py <pfr> <assets out> <js out>"""
import json, re, sys
from PIL import Image
PFR, OUT, JS = sys.argv[1:4]
src = open(f'{PFR}/src/text.c').read()
def widths(name):
    m = re.search(r'static const u8 ' + name + r'\[\]\s*=\s*\{(.*?)\};', src, re.S)
    return [int(x) for x in re.findall(r'\d+', m.group(1))]
fonts = {}
for key, png, wname in [('normal', 'latin_normal', 'sFontNormalLatinGlyphWidths'), ('small', 'latin_small', 'sFontSmallLatinGlyphWidths')]:
    im = Image.open(f'{PFR}/graphics/fonts/{png}.png')
    w, h = im.size
    px = im.load()
    fg = Image.new('RGBA', (w, h), (0, 0, 0, 0)); sh = Image.new('RGBA', (w, h), (0, 0, 0, 0)); fp = fg.load(); sp = sh.load()
    for y in range(h):
        for x in range(w):
            c = px[x, y]
            if c == 1: fp[x, y] = (255, 255, 255, 255)   # foreground mask
            elif c == 2: sp[x, y] = (255, 255, 255, 255) # shadow mask
    fg.save(f'{OUT}/{png}_fg.png', optimize=True); sh.save(f'{OUT}/{png}_sh.png', optimize=True)
    cell = 16 if key == 'normal' else 8
    fonts[key] = {'fg': f'assets/font/{png}_fg.png', 'sh': f'assets/font/{png}_sh.png', 'spacing': 0, 'cols': w // (16 if key == 'normal' else 8), 'cw': 16 if key == 'normal' else 8, 'ch': 16, 'widths': widths(wname)}
# charmap: single chars -> code
cm = {}
for line in open(f'{PFR}/charmap.txt', encoding='utf-8'):
    m = re.match(r"^'(.+?)'\s*=\s*([0-9A-Fa-f]{2})\s*$", line.strip())
    if m:
        ch = m.group(1).replace("\\'", "'")
        if len(ch) == 1 and ch not in cm: cm[ch] = int(m.group(2), 16)
for name, code in [('PK', 0x53), ('MN', 0x54), ('Lv', 0x34)]:
    cm[name] = code
cm['…'] = 0xB0  # ellipsis
with open(JS, 'w') as f:
    f.write('// generated by tools/build_font.py\nconst FONTS = ' + json.dumps(fonts) + ';\nconst CHARMAP = ' + json.dumps(cm, ensure_ascii=False) + ';\n')
print(len(cm), 'chars')
