#!/usr/bin/env python3
"""Extract UI + battle strings, std strings and multichoice lists. usage: build_strings.py <pfr> <js out>"""
import json, os, re, sys
PFR, JS = sys.argv[1:3]
STR = {}
for fn in ['src/strings.c', 'src/battle_message.c', 'src/party_menu.c', 'src/pokemon_summary_screen.c', 'src/item_menu.c', 'src/start_menu.c',
           'src/shop.c', 'src/pokemon_storage_system.c', 'src/battle_script_commands.c', 'src/evolution_scene.c', 'src/naming_screen.c',
           'src/oak_speech.c', 'src/main_menu.c', 'src/option_menu.c', 'src/trainer_card.c', 'src/pokedex_screen.c', 'src/field_specials.c',
           'src/tm_case.c', 'src/item_use.c', 'src/battle_controller_player.c', 'src/new_game.c', 'src/save_menu_util.c', 'src/pokemon.c']:
    p = f'{PFR}/{fn}'
    if not os.path.exists(p): continue
    src = open(p, encoding='utf-8').read()
    for m in re.finditer(r'(?:static\s+)?const u8 (\w+)\[\]\s*=\s*_\((.*?)\);', src, re.S):
        STR[m.group(1)] = ''.join(re.findall(r'"((?:[^"\\]|\\.)*)"', m.group(2)))
    for m in re.finditer(r'(?:static\s+)?const u8 (\w+)\[\]\s*=\s*_\(\s*"((?:[^"\\]|\\.)*)"\s*\)', src):
        STR.setdefault(m.group(1), m.group(2))
bm = open(f'{PFR}/src/battle_message.c', encoding='utf-8').read()
BSTR = dict(re.findall(r'\[(STRINGID_\w+)\s*-\s*BATTLESTRINGS_TABLE_START\]\s*=\s*(\w+)', bm))
sm = open(f'{PFR}/src/script_menu.c', encoding='utf-8').read()
lists = {m.group(1): re.findall(r'\{\s*(\w+)', m.group(2)) for m in re.finditer(r'static const struct MenuAction (\w+)\[\] = \{(.*?)\};', sm, re.S)}
MC = {m.group(1): lists.get(m.group(2), []) for m in re.finditer(r'\[(MULTICHOICE_\w+)\]\s*=\s*MULTICHOICE\((\w+)\)', sm)}
STD = re.findall(r'\[STDSTRING_\w+\]\s*=\s*(\w+)', sm)
# selected data/text files (save prompts, new game intro, pc, mart, white out)
for fn in ['text/save.inc', 'text/new_game_intro.inc', 'text/pc.inc', 'text/poke_mart.inc', 'text/white_out.inc', 'text/trainer_card.inc', 'text/obtain_item.inc', 'text/pc_transfer.inc', 'event_scripts.s']:
    cur = None
    for line in open(f'{PFR}/data/{fn}', encoding='utf-8'):
        m = re.match(r'^(\w+)::', line)
        if m: cur = m.group(1); STR.setdefault(cur, ''); continue
        m = re.match(r'\s*\.string "((?:[^"\\]|\\.)*)"', line)
        if m and cur: STR[cur] += m.group(1)
        elif line.strip() and not line.strip().startswith('.'): cur = None
# move descriptions + ability names/descriptions
md = open(f'{PFR}/src/move_descriptions.c', encoding='utf-8').read()
mdtxt = {m.group(1): ''.join(re.findall(r'"((?:[^"\\]|\\.)*)"', m.group(2))) for m in re.finditer(r'const u8 (\w+)\[\] = _\((.*?)\);', md, re.S)}
MOVE_DESC = {k: mdtxt.get(v, '') for k, v in re.findall(r'\[MOVE_(\w+)\s*-\s*1\]\s*=\s*(\w+)', md)}
ab = open(f'{PFR}/src/data/text/abilities.h', encoding='utf-8').read()
abtxt = {m.group(1): m.group(2) for m in re.finditer(r'static const u8 (\w+)\[\] = _\("((?:[^"\\]|\\.)*)"\);', ab)}
ABIL = {}
for k, v in re.findall(r'\[ABILITY_(\w+)\]\s*=\s*(s\w+Description)', ab): ABIL[k] = ['', abtxt.get(v, '')]
for k, v in re.findall(r'\[ABILITY_(\w+)\]\s*=\s*_\("((?:[^"\\]|\\.)*)"\)', ab): ABIL.setdefault(k, ['', ''])[0] = v
# mapsec names
rm = {}
for sec in json.load(open(f'{PFR}/src/data/region_map/region_map_sections.json'))['map_sections']:
    if 'name' in sec: rm[sec['id']] = sec['name']
with open(JS, 'w') as f:
    f.write('// generated by tools/build_strings.py\n')
    for n, v in [('STRINGS', STR), ('BATTLE_STRING_IDS', BSTR), ('MULTICHOICE', MC), ('STD_STRINGS', STD), ('MAPSEC_NAMES', rm), ('MOVE_DESC', MOVE_DESC), ('ABILITIES', ABIL)]:
        f.write(f'const {n} = ' + json.dumps(v, separators=(',', ':'), ensure_ascii=False) + ';\n')
print(len(STR), 'strings', len(BSTR), 'battle ids', len(MC), 'multichoice', len(rm), 'mapsecs')
