#!/usr/bin/env python3
"""Sound-effect timeline of every move animation, from pret's data/battle_anim_scripts.s.
Each entry is [frame, SE, pan] (pan: -1 attacker side, 1 target side, 0 centre); frames are 60 fps
delays summed along the script (waitforvisualfinish counts as a short gap).
usage: build_movese.py <pokefirered> <js out>"""
import json, os, re, sys, urllib.request
PFR, OUT = sys.argv[1:3]
path = f'{PFR}/data/battle_anim_scripts.s'
if not os.path.exists(path):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    open(path, 'wb').write(urllib.request.urlopen('https://raw.githubusercontent.com/pret/pokefirered/master/data/battle_anim_scripts.s', timeout=60).read())
labels, cur = {}, None
for line in open(path):
    m = re.match(r'^(\w+):', line)
    if m: cur = m.group(1); labels[cur] = []; continue
    if cur is None: continue
    s = line.split('@')[0].strip()
    if s: labels[cur].append(s)
PAN = {'SOUND_PAN_ATTACKER': -1, 'SOUND_PAN_TARGET': 1}
def pan(tok): return PAN.get(tok.strip(), 0)
def walk(label, t, out, depth=0):
    if depth > 6 or label not in labels: return t
    for s in labels[label]:
        op, _, rest = s.partition(' ')
        a = [x.strip() for x in rest.split(',')] if rest else []
        if op == 'delay': t += int(a[0], 0) if a[0][0].isdigit() else 0
        elif op == 'waitforvisualfinish': t += 6
        elif op in ('playsewithpan', 'playse') and a and a[0].startswith('SE_'): out.append([t, a[0], pan(a[1]) if len(a) > 1 else 0])
        elif op == 'loopsewithpan' and a[0].startswith('SE_'):
            for i in range(min(int(a[3], 0), 6)): out.append([t + i * int(a[2], 0), a[0], pan(a[1])])
        elif op == 'waitplaysewithpan' and a[0].startswith('SE_'): out.append([t + int(a[2], 0), a[0], pan(a[1])])
        elif op.startswith('panse') and a and a[0].startswith('SE_'): out.append([t, a[0], 0])
        elif op == 'createsoundtask' and len(a) > 1 and a[1].startswith('SE_'): out.append([t, a[1], 0])
        elif op in ('createvisualtask', 'createsoundtask') and a and 'Cry' in a[0]: out.append([t, 'CRY', -1])
        elif op in ('call', 'goto', 'jumpargeq', 'jumpifcontest'):
            dest = a[-1] if op != 'call' and op != 'goto' else a[0]
            t = walk(dest, t, out, depth + 1)
            if op == 'goto': return t
        elif op in ('end', 'return'): return t
    return t
MOVE_SE = {}
for lab in labels:
    if not lab.startswith('Move_'): continue
    out = []
    walk(lab, 0, out)
    out = [e for e in out if e[0] <= 100][:10]
    if out: MOVE_SE[lab[5:]] = out
with open(OUT, 'w') as f:
    f.write('// generated by tools/build_movese.py from pret/pokefirered data/battle_anim_scripts.s\n')
    f.write('const MOVE_SE = ' + json.dumps(MOVE_SE, separators=(',', ':')) + ';\n')
print(len(MOVE_SE), 'moves with sounds')
